import type { NextPage } from "next"
import Head from "next/head"
import { useMoralis } from "react-moralis"
import Chat from "../components/chat"
import Login from "../components/login"
import { Puff } from "react-loader-spinner"

const Home: NextPage = () => {
  const { isAuthenticated, isInitializing } = useMoralis()

  if (isInitializing && isAuthenticated) {
    return (
      <div className="w-full h-screen flex justify-center items-center bg-gradient-to-b from-[#070207] to-[#4D2053]">
        <Puff color="#c43b6f" height={100} width={100} />
      </div>
    )
  }

  if (!isAuthenticated) {
    return <Login />
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Chat />
    </div>
  )
}

export default Home
